up:
	docker compose up

down:
	docker compose down

build:
	docker compose build

restart:
	docker compose down && docker compose up

rt-build:
	docker compose down && docker compose build && docker compose up